name: insurance_challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.11.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  easy_localization: ^3.0.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  loading_animation_widget: ^1.2.0+4
  pdf: ^3.10.4
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_pdfviewer: ^23.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/resource/
  line_length: 80
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml
  assets:
    enabled: true
    outputs:
      style: camel-case

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kb.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F4F5FF"
  image: assets/images/KB.png
  android_12:
    image: assets/images/KB.png
    icon_background_color: "#F4F5FF"

flutter:
  uses-material-design: true
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/
    - assets/lang/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
