name: insurance_challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  flutter_svg: ^2.0.7
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter_gen:
  output: lib/resource/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      style: dot-delimiter

flutter:
  uses-material-design: true
  assets:
    - assets/images/