// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhBN-tXqHQ_I0gWwVnPjmA4WwR8Y1E6k',
    appId: '1:943794067234:web:0a608b834487151ab8777b',
    messagingSenderId: '943794067234',
    projectId: 'insurance-challenge',
    authDomain: 'insurance-challenge.firebaseapp.com',
    storageBucket: 'insurance-challenge.appspot.com',
    measurementId: 'G-M62325RZJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtisJIKjIeet7oxO4V8p7L2gKL7XNirXY',
    appId: '1:943794067234:android:ea45cd8585b6a8c3b8777b',
    messagingSenderId: '943794067234',
    projectId: 'insurance-challenge',
    storageBucket: 'insurance-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC591TSktg1VWqnxhL75a2Wrh2O383aLM',
    appId: '1:943794067234:ios:c73c939154f6f240b8777b',
    messagingSenderId: '943794067234',
    projectId: 'insurance-challenge',
    storageBucket: 'insurance-challenge.appspot.com',
    iosBundleId: 'com.kartikadev.insuranceChallenge',
  );
}
